# Generated by Django 2.0.2 on 2018-07-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='venta_articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=25)),
                ('precio', models.IntegerField(default=0)),
                ('marca_carros', models.CharField(choices=[('Bmw', 'CarroBmw'), ('Volkswagen', 'CarroVolkswagen'), ('Chevrolet', 'CarroChevrolet'), ('Ford', 'CarroFord'), ('Nissan', 'CarroNissan')], max_length=10)),
                ('descripcion', models.TextField()),
                ('foto', models.FileField(upload_to='')),
            ],
        ),
    ]
