# Generated by Django 2.0.2 on 2018-07-24 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualrec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta_articulo',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
